### ISSUE TITLE
ChainedManyToManyField show as single Select?

### ISSUE THREAD

**Issue by jayache80** [digi604/django-smart-selects#138]
Hello,

My models are set up as Many To Many, and I'm using ChainedManyToManyField. However, there's an instance where I want the user to select only one, not multiple select. When I override the form in forms.py with a widget designating it as Select(), it breaks the Smart Select.

Does anyone know how to properly (and easily) make it so the rendered html makes a single select box, not multiple?

**Comment by blag** [comment]
This is not currently supported, although pull requests are welcome.

**Comment by blag** [comment]
What happens when you explicitly specify `smart_selects.widgets.ChainedSelect` as the widget for the form field you want to customize? See the [Django docs on specifying widgets](https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#specifying-widgets) for how to do this properly.

I think that should work just fine, since the [Django docs on `SelectMultiple`](https://docs.djangoproject.com/en/1.10/ref/forms/widgets/#selectmultiple) indicate the only difference between the `Select` widget and the `SelectMultiple` widget is the HTML `multiple='multiple'` attribute.

**Comment by blag** [comment]
Since it's been 10 months without an update and 6+ months without a response, I'm closing this issue. Feel free to reopen if my workaround didn't work for you or if you still can't figure it out. Thanks!
