### ISSUE TITLE
django-smart-selects does not work when Jquery file is loaded at the bottom of the page

### ISSUE THREAD

**Issue by bryankimani** [digi604/django-smart-selects#143]
Can someone kindly guide me on how I can make the django-smart-select to work when my jquery file is loaded at the bottom of my base.html.

N:B It only works when I load it at the head part of my of my base.html. 
It is best practice to place scripts at the end of the document so the pages load faster

**Comment by shtalinberg** [comment]
I have the same problem

**Comment by blag** [comment]
This is not currently possible due to the way DSS includes Javascript in the widget rendering. See [widgets.py:119](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L119-L132) and [widgets.py:245](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/widgets.py#L245-L260).

I'll look into seeing if we can refactor to support this.

**Comment by blag** [comment]
This should be fixed once #96 is merged in.

**Comment by SalahAdDin** [comment]
@blab what's about it?

**Comment by blag** [comment]
PR #96 needs to be rewritten to cleanly merge. I don't have time to properly refactor the javascript out, but it shouldn't be too difficult if somebody else wants to take the lead on this.

@SalahAdDin Also, my name is "blag" with a 'g' at the end. 😜

**Comment by SalahAdDin** [comment]
jajajajajaj, sorry.

**Comment by blag** [comment]
This should now work with version 1.4.0+. Please test it and report back (and reopen the issue if necessary).

If you are including jQuery separately you can set `JQUERY_URL` to `False` so `smart_selects` doesn't include it.
