### ISSUE TITLE
Can't set 'country' field in 'Location' Model to "blank=True, null=True"?

### ISSUE THREAD

**Issue by GoTop** [digi604/django-smart-selects#146]
Take the Continent-Country example from README file of this module:

```
class Continent(models.Model):
        name = models.CharField(max_length=255)

class Country(models.Model):
        continent = models.ForeignKey(Continent)
        name = models.CharField(max_length=255)
class Location(models.Model)
    continent = models.ForeignKey(Continent)
    country = ChainedForeignKey(
        Country, 
        chained_field="continent",
        chained_model_field="continent", 
        show_all=False, 
        auto_choose=True
        # I add the below code
        null=True, 
        blank=True
    )
```

when I set "null=True, blank=True" to the 'country' field of 'Location' Model, but it doesn't work.

on the  'Location' Model admin change page, when I don't select value for  'country' field, left it to be "------" and save.

this error infomation show:
```
IntegrityError at /admin/app_name/location/1/change/

app_name_location.country_id may not be NULL
```

**Comment by millin** [comment]
@GoTop, is this issue happened on my repo or on this repo too?

**Comment by GoTop** [comment]
@millin, I use your repo currently, so it is happen on your repo.

and I think maybe this issue is common in all the django-smart-selects repo. 

I will test it on this repo when I get home tonight and I will let you know the result.

**Comment by blag** [comment]
Any update on this?

**Comment by blag** [comment]
When you changed the `blank=True, null=True` in the test app, did you also create and run the migrations to write that change to the database?

The `IntegrityError` that you're getting is from the database, because the database columns still have `NOT NULL` constraints on them.

I'm pretty sure this is the issue, so I'm going to close this. If you're still having the problem, check the following things:

* Verify that `python manage.py makemigrations` doesn't create any more migration files
* Verify that `python manage.py migrate` doesn't migrate any more tables
* Verify that your database constraints allow those columns to be `NULL`

If you verify all of those things and the problem still happens please feel free to reopen.
