### ISSUE TITLE
Smart selects and MPTT

### ISSUE THREAD

**Issue by fankertiban** [digi604/django-smart-selects#164]
Hello! I need to chain a field which is actialy a TreeForeignKey from MPTT module. And I have no idea how to do that except the multiple inheritance, but it seems to me that there are some more easy and beautiful ways.
Any thoughts?

**Comment by blag** [comment]
Multiple inheritance actually sounds pretty elegant to me. Python's multiple inheritance does not suffer from many of the problems of MI in other languages, notably C++.

Things to consider and make sure you understand:

1. Python's method resolution order ([MRO](https://python-history.blogspot.com/2010/06/method-resolution-order.html))
2. How to use [`super()`](https://rhettinger.wordpress.com/2011/05/26/super-considered-super/) correctly

I checked out the code for `TreeForeignKey`, and you should be fine as long as you keep the `TreeForeignKey` before `ChainedForeignKey` in the parent class list:

```python
class ChainedTreeForeignKey(TreeForeignKey, ChainedForeignKey):
    # ...
```

If you have any problems integrating the two please create issues, or (more preferably PRs). Also, if you figure anything out that would save other people time, let me know and I'll add it to our documentation. And if you write anything that other people can use, I'll add it to the project.

I'm going to close this issue since I think that answers your question with sufficient detail, but if you have any additional questions (or need any more detail) about how to get MPTT and DSS to play together well, please feel free to reopen it.

Thanks and good luck! 😄

**Comment by blag** [comment]
Actually, looking at it a bit closer, you will **also** need to create a form field that subclasses from both `mptt.forms.TreeNodeChoiceFieldMixin` and `smart_selects.form_fields.ChainedModelChoiceField`:

Your `forms.py` or your `form_fields.py`:
```python
class ChainedTreeNodeChoiceField(TreeNodeChoiceFieldMixin, ChainedModelChoiceField):
    pass
```

And then you'll need to override `formfield()` on `ChainedTreeForeignKey`:

```python
class ChainedTreeForeignKey(TreeForeignKey, ChainedForeignKey):  # From previous comment
    # ...
    def formfield(self, **kwargs):
        kwargs.setdefault('form_class', ChainedTreeNodeChoiceField)
        return super(ChainedTreeForeignKey, self).formfield(**kwargs)
```

If this works for you let me know and I'll write it into the documentation. This sounds like an excellent addition (presuming it works). Thanks!

**Comment by blag** [comment]
Hey @fankertiban, did this work for you?
