### ISSUE TITLE
XSS in select dropdowns

### ISSUE THREAD

**Issue by samupl** [digi604/django-smart-selects#171]
During our testing, @KubaGorski found a XSS vulnerability in the select dropdown rendering. 

The bug is found in [chainedfk.js#L41](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/static/smart-selects/admin/js/chainedfk.js#L41) and [chainedm2m.js#L54](https://github.com/digi604/django-smart-selects/blob/master/smart_selects/static/smart-selects/admin/js/chainedm2m.js#L54).

You can trigger the XSS while having a model with `__str__` method that returns arbitrary javascript code, and can be dangerous if have chained models with `__str__` methods using fields that are filled in by users, for example:

```python
class Comment(models.Model):
    text = models.CharField(max_length=128)
    
    def __str__(self):
        return self.text
```

And if the `text` field contains something like `Lorem ipsum <script>alert(123)</script>`, the javascript code will be executed in the django admin interface, which can lead to data leak, credential stealing or attacks on particular browser vulnerabilities of the site admin.

**Comment by samupl** [comment]
I have created a pull request that fixes this bug: https://github.com/digi604/django-smart-selects/pull/172

**Comment by blag** [comment]
I will upload a new release to PyPI containing this fix, and remove previous (insecure) versions from PyPI.

Thanks for your help!

**Comment by samupl** [comment]
You're welcome ;)

**Comment by blag** [comment]
Your changes are in version 1.2.**8** and are now on PyPI.

#### People reading this in the future ####

I dug through the history - this has been a security flaw since the first initial commit, so I removed all versions below 1.2.8 from PyPI. I know this will break people's builds, and I'm sorry. Please upgrade to version 1.2.8 or higher (whatever the latest version is). If you truly need to use any previous versions, you can specify the commit to use. See this [Stack Overflow post for examples](http://stackoverflow.com/a/13754517/6461688), but I am making this difficult for a reason: **you should not do this**.
