### ISSUE TITLE
pip installation fails for `django-smart-selects==1.1.1`

### ISSUE THREAD

**Issue by rmhasan** [digi604/django-smart-selects#174]
Hi I am working on a project that has `django-smart-selects==1.1.1` in it's `requirements.txt` file and it fails here with `Could not find a version that satisfies the requirement django-smart-selects==1.1.1 (from -r requirements.txt (line 18)) (from versions: 1.2.8)
No matching distribution found for django-smart-selects==1.1.1`.  Does this have something to do
 with issue #173 ?

**Comment by blag** [comment]
https://github.com/digi604/django-smart-selects/issues/171#issuecomment-276774103

**Comment by blag** [comment]
Sorry, hit the close button too early.

No, I removed all insecure versions from PyPI because you really, really should not be using them.

You can build the version you want from the exact git commit. I linked to examples of how to do that in the comment I linked to.

I am currently trying to fix build errors caused by #173. That should be done by tonight.

**Comment by rmhasan** [comment]
Thanks @blag

**Comment by blag** [comment]
I fixed the build errors in #173; you should be able to install 1.2.9+.
