### ISSUE TITLE
Inconsistent release history

### ISSUE THREAD

**Issue by beruic** [digi604/django-smart-selects#185]
The [releases page](https://github.com/digi604/django-smart-selects/releases) here on Github currently shows v1.2.2 as newest version, but the [release page on Pypi](https://pypi.python.org/pypi/django-smart-selects/) currently has v1.3.2 as the newest version.

**Comment by beruic** [comment]
Also, I can't find a changelog anywhere. Shouldn't there be one attached at Pypi so you don't have to find the commit log here on Github?

**Comment by blag** [comment]
The recommended way of installing this is through pip, which should automatically use the latest version on PyPI. Is there a particular reason you want to use a previous release?

Keep in mind that releases < 1.2.9 have been removed from PyPI to prevent users from installing insecure versions of d-s-s: https://github.com/digi604/django-smart-selects/pull/172

I have not removed the previous releases from GitHub simply because I never realized that page existed. I would like to create a new release on GitHub based on 1.3.2 and remove all previous GitHub releases, so the GitHub releases match the PyPI ones. Will that work for you?

I have been meaning to convert the readme to RestructuredText, which would render correctly in PyPI. When I do that I'll throw in a release changelog.

**Comment by beruic** [comment]
>  I would like to create a new release on GitHub based on 1.3.2 and remove all previous GitHub releases, so the GitHub releases match the PyPI ones. Will that work for you?

Yes, this is exactly what I am looking for :)

Also, it would be nice if you sometime in the future wrote the changelog on each release (see https://github.com/dfunckt/django-rules/releases for an example), but I can live without. The thing is that I track third party releases using atom feeds from github. You can find your own at https://github.com/digi604/django-smart-selects/releases.atom

**Comment by blag** [comment]
As of release 1.3.3, both releases should be on PyPI and GitHub. PyPI releases should be signed with my public key.

I have now removed all previous (<1.3.3) releases and tags from GItHub.

Do you specifically want a separate changelog or would it be fine if I just put the changes in the GitHub release notes?

**Comment by beruic** [comment]
I'm fine with whatever is the easiest for you, as long as I can find the changelog, and I am notified of new releases :)

**Comment by beruic** [comment]
Looks good so far :)

**Comment by blag** [comment]
I'm a little lazy so I'd prefer to just put stuff in the release notes and not do an official changelog I have to update all the time.

So, I'll continue to do PyPI+GitHub releases, period. But if, after a few more releases, you find that's not really working for you and you need an official, separate changelog just reopen this issue and we'll go from there.

Thanks! 😃

**Comment by optiz0r** [comment]
I might be being blind, but since the releases were pulled from pypi/github, is there any way to find out the summary of what changed between 1.0.x and 1.3.x in order to do an upgrade, short of comparing the readme files side by side at each revision?

**Comment by blag** [comment]
There's no quick/easy way to do so, no.

You can check out the git log from version any version (here, [1.0.9.1](https://github.com/digi604/django-smart-selects/commits/master?after=Y3Vyc29yOrSgW1A9T%2BYvzYWWfrJVuf0TUteUKzEzOQ%3D%3D)) to HEAD:

```bash
git log --pretty --oneline f2d4dd533823b6f6a26d6978fa0bb0789d4bc782..HEAD
```

The highlights are (ordered - sort of - from most important to least important):

* Support Python 3
* Support Django > old
* Add tests, Travis, and coverage/Coveralls
* Fixed a BUNCH of stuff
* Allowed UUIDs (serialize non-integer primary keys to strings)
* More support for Django admin, including `filter_horizontal`
* Change `.attr('selected', 'selected')` to `.prop("selected", true)`
* Send cache control headers to prevent browsers from caching JSON results - closes #52
* Support primary keys that aren't called `id`
* Explicitly include static files in the manifest, so building from source and installing with pip+git works properly
* If sort is False or if Model.Meta specifies ordering, don't sort the view results

Given the XSS bug, I strongly recommend that you to upgrade ASAP.

Don't hesitate to ask more questions! 😄 

----------------------------

Here are full results:

b4a05b5 Bump version to 1.3.4 for PyPI release
9306115 Merge pull request #188 from igr-santos/fix-chained-charfield-django1.8
8e80e70 Fix comments in text to flake8
09750b7 Fix when is_pre_19_syntax is false
05785bf Merge branch 'master' into fix-chained-charfield-django1.8
568c7df Add tests for chained charfield
db74be0 Ignore .env files
d8b7999 Merge pull request #186 from blag/uuid-fix
b58f7ae Merge pull request #183 from jorgecorrea/master
0156f95 Bump version for PyPI release
f299de9 Formatting fixups and add flake8 to Travis tests
235b744 Serialize non-integer primary keys to strings
ab725d8 Merge pull request #182 from savoirfairelinux/bugfix2
a762c9d little change for empty list
775d3c1 little changes and added some comments in code
c09db3b Bugfix for ChainedSelectMultiple
84a0400 Update to explain my patch
e952c7d changes to allow use smartselect mixed width django admin horizontal filter
94fe4fe first changes to have horizontal filter view form
6626e64 Merge pull request #181 from savoirfairelinux/bugfix1
64fe31c Fixed bug - duplication of jquery imports.
db8a097 Merge pull request #180 from jimkutter/master
1497a04 Include the migration script to create js error models, add migrate step to travis
4f817d6 Create scenario for null initial_value when using many to many and fix
b43a37d Fix attribute error when field filtered not is foreignkey
9eb75a5 Bump version for new PyPI release
ed97d5c Flake8 fixups
8b3a681 fix regression after 7fe77bbf21ccdbc34984364b0adcc6e122e105c1 (fixes #175) (#176)
c9becdf Bump version to put documentation on PyPI
d31fa0a Add issue template for GitHub
2cc2532 Don't recursively include dist/ when building packages
789c402 Don't distribute __pycache__ directories
f934a64 Tell PyPI to use README.md as description file
615b92a Bump version for new PyPI release
52bc3b0 Fix XSS in select dropdown rendering (#172)
9a04cc7 Fix selects (#168)
d5597a1 Bump version for PyPI release
f0aaca9 Tweak javascript to fix #167
d42bfe9 Change .attr('selected', 'selected') to .prop("selected", true)
beb84d6 Fix double selected attribute in chained selects
d78bcf0 Fix - trigger chosen:update when value is empty
1e8a7bf chainedm2m with proper selected highlighting (#160)
0bbf381 Bump version for PyPI release
51f83fd Explicitly include static files in the manifest, so building from source and installing with pip+git works properly
cc613dd Test using strings (as well as imported model classes) in test_app
15d3d6e Fix using strings as relations
c711238 Use super() instead of calling methods on superclasses directly
46f651b Send cache control headers to prevent browsers from caching JSON results - closes #52
2317b8f Convert the last HttpResponse to a JsonResponse
f6b46a8 Add test for reverse relationship manager
898640c Lint our JS
4305e2d Merge remote-tracking branch 'rantecki/rantecki_20160725'
344811d Bump version for new PyPI release
e73e098 Allow chained fields to specify 'self' as a relation
7cecb1f Bump version before PyPI release
bb721b4 Merge pull request #151 from millin/inlines
f82d5b2 Fix issue with Inlines M2M. Close #150
5b498a0 Update setup.py to include required information
3ffc87d If sort is False or if Model.Meta specifies ordering, don't sort the view results
bcc56a9 Merge pull request #148 from millin/inlines
9b8f0d4 Fix issue with Inlines. Close #136
f474f47 Don't load jQuery if JQUERY_URL is False
884c769 Some objects will have a pk but not an id.
6d31f49 Merge remote-tracking branch 'johtso/fix-widget-media' into merges
1868dbf Merge a modified c5fd5adb900d2e130aa6b266d2ce416dab394e81 to use item.id (serializes UUIDs) instead of item.pk (doesn't serialize UUIDs)
7ceee33 Merge pull request #133 from yacme/yacme
84967c1 Merge pull request #141 from halfnibble/master
2bb8524 Fix python 3 compatibility issue
fb78e69 Encode JSON with the Django encoder
1444107 Update version. Deprecate Django 1.7. Include Django 1.10 and Python 3.5.
cfbe934 Modify Select widgets to be compatible with Django 1.10 widgets.
c631f22 Add support for Chained M2M when parent is a ManyToManyField.
eee67c2 Use mixin
8f2ad11 Fix dynamic media property
2ecfe88 Merge branch 'fix-grappelli-dom-bug' of https://github.com/olivierdalang/django-smart-selects into olivierdalang-fix-grappelli-dom-bug
21cd434 [fix] update jquery version to 2.2.0
15e3b7b Fix link to jquery for Django 1.9
0e42c89 fix ValueError running collectstatic on django 1.9 DEBUG=False
7b5fd40 Merge branch 'master' of https://github.com/digi604/django-smart-selects
7eb13fc [feature] revise version number
e350e14 Merge branch 'issue_fix'
01e5f55 [feature] add test for grouped select
9fe7062 [fix] fix python 3 syntax error
65b43cd [feature] add migration file
bd92b91 [feature] add more test
82a1307 [feature] add more test
ca38506 Update README.md
ea90077 [feature] revise version number
e0112d1 [fix] remove token
2d9ad89 [feature] revise coveralls token
c57b7c6 Merge branch 'post_blank_data_fix' of https://github.com/PetrDlouhy/django-smart-selects into PetrDlouhy-post_blank_data_fix
bb8c7eb flake8 syntax fix
1711c40 fixup! add test application and improve testing
3a36897 add Django 1.7 to tests, as it is working out of the box
9142b38 fix Django 1.10 warning - get_field_by_name -> get_field
7096768 test filterchain views
8720cc2 fix tests in Python 3
a5466a4 fix error when saving with blank value, test it
c6b0855 update README according to tests
ea651df Django 1.10 compatibility fix - urls.py
0fe96e4 add test application and improve testing
910e2ec Merge branch 'tests' of https://github.com/PetrDlouhy/django-smart-selects into PetrDlouhy-tests
d5e7138 fix tests in Python 3
f3fd955 extend .gitignore
1949a7e add Coveralls configuration
caddced fix tests
f299594 add Travis configuration
6285bbf flake configuration, fixes
da521bc Merge remote-tracking branch 'joel/master' into tests
3bda12f Update README.md
a81ace9 Refactored URLs according to newer versions of Django
8072b83 [fix] change version number
e89812f Merge branch 'issue_fix'
ce86ef3 [fix] add support to django 1.9
25e607e [fix] remove clean method in chainedManyToMany formfield
6833514 [fix] remove unused params in chainedmanytomany, remove unused _get_choices method
6b53c21 [fix] remove unused code in chainmanytomany widget
28b75c5 [refactor] change variable name to make it more readable
bf5d66c [fix] fix get choices api error when the initial value of chained_field is empty
27f3a1a [refactor] remove unused code
2524fe0 [refactor] rename some argument name; write some comments for clarification purpose
766b6bb [refactor] move the javascript of chainedforeignkey to js file
e2b520c Merge branch 'PetrDlouhy-master' into issue_fix
d8d6f24 [fix] fix merge conflict after merging ChainManyToMany
d019404 Merge branch 'manytomany' of https://github.com/savoirfairelinux/django-smart-selects into issue_fix
31f3ad2 fix display issue with grappelli
d65f809 fix for Django 1.9: import get_model
4504575 Refer to ChainedManyToManyField
e27ec86 [fix] fixed issue #58; remove print, revise sort method for python 3 compatibility
63c37d5 [fix] issue #58, add limit_choices_to support for chained_field with show_all option
97c0793 [fix] add support for limit_choices_to in ChainedForeignKey field
87a4d9f change version to 1.1.1
5d77e74 add import forcetext
b726a81 change unicode to forcetext for python3 compatibility
981cc89 Merge branch 'SalahAdDin-master'
afb5e79 Merge branch 'master' of https://github.com/SalahAdDin/django-smart-selects into SalahAdDin-master
4e5f727 Fix conflict errors with django admin
e0ded22 Fix basestring error.
98a675f Fix warning Django 1.9
189909c Fix warning Django 1.9
f5f4957 Fix unicode error
df4cdbf update version to 1.1.0
4293028 chainedm2m: move javascript to external js file
6d7146f Add support for south migrations
2377ea4 Defines ChainedSelect media using a dynamic property.
7a172b9 Implement ChainedManyToMany
dc23903 _assert_reconstructible -> assert_reconstructible.
b1e8ab6 Simplifies Django version check.
cd37166 Skips deconstruct tests on < Django 1.7.
38ab1f7 Adds test script and basic tests of deconstruct() methods.
f5f7b82 Merge pull request #68 from joelcrocker/master
025578d Fixes handling of GroupedForeignKey's group_field arg in deconstruct().
9dce64a Adds deconstruct() methods to both custom Field classes.

**Comment by optiz0r** [comment]
Thanks for the quick and detailed response. It's an argument I think for keeping the content of the "github release notes" as a file tracked in the repository, since otherwise if you ever have to pull versions again for security issues, the release notes are gone along with any users's upgrade instructions.

I am using (possibly internal) `ChainedModelChoiceField` directly in forms and the constructor has changed quite significantly between versions (addition of the foreign_key_* fields) so I'll have to dig through the code to find out what changes are needed on my side.

**Comment by SamuelMS** [comment]
@blag I agree with what seems to be the general sentiment here -- I think it would be very useful for this project to have a changelog to track breaking changes, new features, etc -- even if it's just as simple as listing the output of the `git lot` command that you recommended a few posts ago.

**Comment by blag** [comment]
@SamuelMS In tandem with pushing releases to PyPI I have been publishing releases on GitHub, which provides an Atom feed of releases. Those each have a high-level changelog.

If you wish to see a detailed changelog from `git log`, you can simply view the commits page on GitHub: https://github.com/digi604/django-smart-selects/commits/master

**Comment by SamuelMS** [comment]
@blag Perhaps my release history on GitHub was cached, since I checked before commenting here -- the latest displayed was version `1.4.0`. I see the new version now, thanks.

**Comment by blag** [comment]
No, sorry, that was my fault. I forgot to make the GitHub release after pushing to PyPI. I'm barely responsible enough to make GitHub releases in tandem, so you can only imagine how out of date an official changelog would be. 😆
