### ISSUE TITLE
Illogical foreign keys in child models

### ISSUE THREAD

**Issue by eriktelepovsky** [digi604/django-smart-selects#189]
What is the point of saving all parent models foreign keys into the child model? It is not a good/logical approach.

## Steps to reproduce
Use continent, country and location models mentioned in the readme demo. The country model is already related to the continent, so we shouldn't store a continent foreign key into location model, right?

## Expected behavior
Each child model should have foreign key to nearest parent model only.

## Actual behavior
Child models have foreign keys to all parent models in its hierarchy.

**Comment by blag** [comment]
You're not wrong, but frankly, I don't see why it matters. It's the example/test project, nothing more. As long as the example shows people how to use it then it fulfills its task. It doesn't impact any of the functionality of the project, so why do you care?

That being said, since you raise a valid point, I'd be happy to look at a pull request that had a more sensible example/test app and was equally as immediately understandable as the current one.

Closing, since I don't think it matters, and if it does matter the better way can go in a PR. Thanks!
