### ISSUE TITLE
Error with add new Inline form

### ISSUE THREAD

**Issue by ballbrk** [digi604/django-smart-selects#192]
Hi, 
I've this Inline

class EstateQualityEstateInline(admin.StackedInline):
    model = EstateQualityEstate
    extra = 2
    suit_classes = 'suit-tab suit-tab-quality'

class EstateQualityEstate(models.Model):
    estate = models.ForeignKey(Estate)
    estate_quality = models.ForeignKey(EstateQuality, related_name='estate_quality_estate')
    estate_quality_options = ChainedForeignKey(
        EstateQualityOptions,
        chained_field="estate_quality",
        chained_model_field="estate_quality",
        show_all=False,
        auto_choose=True,
        related_name='estate_quality_options_estate'

    )

The code selects works fine for the two inline forms created. But when I click on "Add new form" in the inline. The new form don't populate the chained field.

**Comment by blag** [comment]
I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. Feel free to reopen this issue once you have filled out the issue template at:

https://github.com/digi604/django-smart-selects/blob/master/.github/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

Once you have done that I will take a look at this issue. Thanks!

**Comment by blag** [comment]
Please format your code with [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) by using fenced blocks:

    ```python
    def this_python_function():
        # Get rendered properly
        return awesome
    ```
gets rendered as:

```python
def this_python_function():
    # Get rendered properly
    return awesome
```

**Comment by blag** [comment]
Re-reported (properly) in #193.
