### ISSUE TITLE
Which versions of Django does the project support?

### ISSUE THREAD

**Issue by mattayes** [digi604/django-smart-selects#195]
## Checklist

- [X] This issue is not about installing previous versions of django-smart-selects older than 1.2.8. I understand that previous versions are insecure.
- [X] I have verified that that issue exists against the `master` branch of django-smart-selects.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] I have debugged the issue to the smart_selects app.
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included all relevant sections of `models.py`, `forms.py`, and `views.py` with problems.

## Issue

Hi folks, I'm trying to upgrade from VERY old versions of Django (1.4) and django-smart-selects (1.1.1). Which versions of Django do you currently support? Which versions did previous releases support? Thanks for you help!

**Comment by blag** [comment]
> Which versions of Django do you currently support?

We run tests against all "modern" versions of Django: those that currently have support from the Django developers. See the dependencies in the [`.travis.yml` file](https://github.com/digi604/django-smart-selects/blob/master/.travis.yml#L4) for exactly what versions we are compatible with.

> Which versions did previous releases support?

Our current set of supported Django versions hasn't changed since version 1.2.8 came out (which was a security release). Not only would this question force me to dig through the commit history, I simply don't want to answer it because it would enable you to use older, insecure versions of django-smart-selects. I *highly* recommend you use version 1.2.8 **at minimum**, and note that there hasn't been any huge or breaking changes since then.

Closing since I've kind of answering your question. Feel free to ask more (but please keep them in this issue if they're related to it)!

**Comment by blag** [comment]
You're welcome; glad you found the answer you were looking for. 😄
