### ISSUE TITLE
'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by brayan15** [digi604/django-smart-selects#235]
hello, I have a problem, this is my model:
from smart_selects.db_fields import ChainedForeignKey

city = ChainedForeignKey(City,
        chained_field="state",
        chained_model_field="state",
        show_all=False)

also I added url and jquery on settings

**Comment by blag** [comment]
I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. Feel free to reopen this issue once you have filled out the issue template at:

https://github.com/coderholic/django-cities/blob/master/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

Once you have done that I will take a look at this issue. Thanks!

(These pictures are just examples from a different repository but the process is the same.)

Also, please format your code with [GitHub Flavored Markdown](https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting) by using fenced blocks:

    ```python
    def this_python_function():
        # Get rendered properly
        return awesome
    ```
gets rendered as:

```python
def this_python_function():
    # Get rendered properly
    return awesome
```

**Comment by duxiaoyang06** [comment]
I occured the same problem when I installed the package .
Part of the error info ：File "/usr/local/Cellar/python3/3.6.2'/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/forms/widgets.py", line 88, in absolute_path

**Comment by duxiaoyang06** [comment]
Do you have solved this problem? @brayan15

**Comment by markddavidoff** [comment]
To summarize for those having this issue, this happens if you set the `JQUERY_URL = True` as it looks like it is expecting a value not a boolean. 

setting Use USE_DJANGO_JQUERY = True instead of JQUERY_URL = True in your settings.py as recommended in
https://stackoverflow.com/questions/61727169/django-smart-selects-not-working-properly worked for me.

**Comment by luzdealba** [comment]
> setting Use USE_DJANGO_JQUERY = True instead of JQUERY_URL = True in your settings.py as recommended in https://stackoverflow.com/questions/61727169/django-smart-selects-not-working-properly worked for me.

That did it for me.
