### ISSUE TITLE
Loading failed for the <script> with source “http://0.0.0.0/static/smart-selects/admin/js/chainedm2m.js”. add:20

### ISSUE THREAD

**Issue by ShubhamSarda** [digi604/django-smart-selects#255]
Followed All Steps As Stated But Everytime Not Able To Load Both Required Scripts. 

Loading failed for the <script> with source “http://0.0.0.0/static/smart-selects/admin/js/chainedm2m.js”.
add:20
Loading failed for the <script> with source “http://0.0.0.0/static/smart-selects/admin/js/bindfields.js”.

**Comment by ShubhamSarda** [comment]
Also Done collectstatic, Added Files Separately. 

New Errors - 
ReferenceError: chainedm2m is not defined[Learn More]
bindfields.js:14:13

**Comment by blag** [comment]
I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. Feel free to edit your description with the issue template at:

https://github.com/coderholic/django-cities/blob/master/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

Please include excerpts from any relevant files, a list of troubleshooting steps you have already taken and their results, and any other information that might help me figure out the problem.

Once you have done that I will reopen and take a look at this issue. Thanks!

(These pictures are just examples from a different repository but the process is the same.)
