### ISSUE TITLE
StopIteration exception when using with django-cities-light

### ISSUE THREAD

**Issue by jorgicio** [digi604/django-smart-selects#40]
Hi!

When I'm using django-cities-light with smart-selects, happens something like this:

http://pastebin.com/5wVXx77e

I followed the instructions of usage of both plugins.

Thanks.

**Comment by blag** [comment]
Since it's is so old I'm going to close this issue.

If this is still happening, please post relevant excerpts from your problematic `models.py`, your Python/Django/django-smart-selects/django-cities-light versions, any information in your browser console, the full traceback, and any other helpful troubleshooting information.

Thanks!
