### ISSUE TITLE
Reverse relationship undefined?

### ISSUE THREAD

**Issue by wilburluce** [digi604/django-smart-selects#42]
It seems there is no reverse relationship manager defined..

```python
class A
    brel =  ChainedForeignKey(B, ...)

class B

    def test(self)
        self.a_set.all()  #  <--- undefined
```

If I change it to `models.ForeignKey` it works...

Edit (by blag): Formatted with GFM.

**Comment by blag** [comment]
I [just added](https://github.com/digi604/django-smart-selects/commit/f6b46a8dede7f40f753159885d2d3b0a203c6781) a test for this:

```python
self.assertEqual(list(cr.location_set.all().values_list('city', flat=True)), ['Praha'])
```

and [it's passing](https://travis-ci.org/digi604/django-smart-selects/builds/169710924).

Due to that and the age of this issue I'm going to close it.

If you're still having this problem please reopen it and add more information, like excerpts from your problematic `models.py`, a full traceback, Python/Django/django-smart-selects versions, and any other troubleshooting information that might be helpful. Thanks!
